title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: minima
remote_theme: pages-themes/minima@v2.5.1
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one